### ISSUE TITLE
Add Warp UI Testing Guide to Runbook

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#113]
```[tasklist]
### Tasks
- [ ] Create QA Guide for Hyperlane India to test (browsers/mobile, wallets)
- [ ] Create funding process for QAing - Avi & Jon - deprioritize
```

Deprioritized
- E2E (keyfunding, fork)

**Comment by avious00** [comment]
@jmrossy let's restrict this to an internal testing guide vs HypIndia

**Comment by jmrossy** [comment]
Added info the internal testing guide in the runbook which should suit our needs for now. Per our discussion, we can expand on that if/when more QA capacity is brought onboard
