### ISSUE TITLE
Investigate & prototype `WarpCore` engine 

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#116]
see parent issue for reducing warp ui tech debt

to be reviewed by yorke, kunal, paul

**Comment by nambrot** [comment]
Is this is ticket to create a proposal to move more of the token adapter logic into the SDK that we talked about? If so, the title feels kinda different?

**Comment by avious00** [comment]
discord discussion thread here: https://discord.com/channels/935678348330434570/1201967815343747152
