### ISSUE TITLE
Implement `WarpCore` engine

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#129]
Building on research in https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/116 and [Discord discussion](https://discord.com/channels/935678348330434570/1201967815343747152) decision

**Comment by avious00** [comment]
@jmrossy to create a small follow up ticket for Paul to expose through CLI

**Comment by jmrossy** [comment]
@avious00 Done, see https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3259
