### ISSUE TITLE
Message signed on the wrong chain

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#148]
### Context
A user ended up signing a warp route transfer intended from inEVM on zkSync ⁠[[discord](https://discord.com/channels/935678348330434570/1217928354871640187/1217928354871640187)]

### Investigation
As per [zksync](https://explorer.zksync.io/address/0x26f32245fCF5Ad53159E875d5Cae62aEcf19c2d4) and [etherscan](https://etherscan.io/address/0x26f32245fCF5Ad53159E875d5Cae62aEcf19c2d4 ) this happened a few times on other chains as well.

@jmrossy suspects imperfect wallet switching behavior within https://github.com/wevm/wagmi for this. 

### Potential Solutions
Some workarounds are:
1. adding more explicit wallet chain checks after switching (possibly hacky)
2. upgrading to wagmi 2
3. Possibly more user prompts to make sure that they are signing on the right chain (unfortunately wallets don't indicate the presence of calldata for a call to a non-existing contract)

**Comment by avious00** [comment]
Opened issues with underlying library + wallet here:
Wagmi https://github.com/wevm/wagmi/issues/3720
Metamask https://github.com/MetaMask/metamask-extension/issues/23568

**Comment by jmrossy** [comment]
We've just upgraded to wagmi v2 for the latest stability and bug fixes. Re checks, we do already query the wallet's current chain before signing. Closing.
