### ISSUE TITLE
Add xERC20 token standard support to WarpCore

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#155]
### Context
We are adding support for open token standards, including xERC20 and Bridged USDC https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3486

### Task
Based on the smart contract changes in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3618
- We need to add first-class support in our tooling, including deployment via SDK/CLI and the Warp UI.
- Update deploy warp route & warp UI docs as well as example files

**Comment by avious00** [comment]
@alexwhte @LayneHaber this should land next week

**Comment by yorhodes** [comment]
afaik this is done @avious00

**Comment by avious00** [comment]
closing this since work seems minimal, mostly testing it works: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3781
