### ISSUE TITLE
Upgrade Wagmi, Viem, Cosmos-kit, and Solana libs

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-warp-ui-template#173]
- Replace Wagmi, Viem, and RainbowKit with v2 versions
- Upgrade cosmos-kit to latest for bug fixes
- Consider upgrading other cosmos libs such as cosmjs (may cause issues for injective patch)
- Upgrade @solana/* libs for bug fixes

Preferably, these upgrades are made in unison with upgrades for the SDK's libs to avoid duplicate versions getting bundled.

Related, see discussion here: https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/153#issuecomment-2147828409

**Comment by YanYuanFE** [comment]
https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/285
