### ISSUE TITLE
Show chain connection status banner in transfer form

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-warp-ui-template#215]
Outdated but roughly correct mockup:

<img width="519" alt="Screenshot 2024-11-05 at 2 20 54 PM" src="https://github.com/user-attachments/assets/b90dc0bf-bcc4-40ab-8782-46c8749b54cb">

Similar to what the ChainWalletWarning but make a new ChainConnectionWarning banner that will test the RPC health for the two selected chains. Use `isRpcHealthy` from the SDK

**Comment by avious00** [comment]
@jmrossy just curious, this is related to flaky rpc urls?

**Comment by jmrossy** [comment]
@avious00 Yes, it's to test and surface RPC flakiness earlier to the user
