### ISSUE TITLE
Add spaceship animation to transaction flow

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-warp-ui-template#276]
Hyperlane's Warp UI template is a great open source way to create a user-facing token bridge. But you know what's also great? **Spaceships.** 

So let's give the people what they want: an open source bounty for adding spaceships to the warp ui template's usenexus.org branch.

The initial animation should be triggered when the tx first begins on the origin chain, and completes with the spaceship animation when the recipient balance increases after the tx is completed on the destination chain.

Here are the spaceship and other assets in [Figma](https://www.figma.com/design/jC5NORmNDCl6WZgjIRwKX5/Hyperlane-Brand-Assets-%5BExternal%5D?t=U5P8EBUoQOLx43jw-0)

![spaceship](https://github.com/user-attachments/assets/2da1e8f1-e170-4944-abfa-315b6fd1cbb2)

**Comment by VividhPandey003** [comment]
Hey @avious00, I'm relatively new to the concept of bounties. Could you explain what they are? Also, could you provide more details on the issue? I'd like to get a clearer understanding so I can determine whether I’ll be able to contribute and give you a definite yes or no upfront.
