### ISSUE TITLE
Improve Chain picker UX

### ISSUE THREAD

**Issue by dovvvv** [hyperlane-xyz/hyperlane-warp-ui-template#277]
It would be great to improve the site's UX by displaying the available routes in an organized way. Active and available routes should be listed first, in an ordered list. The routes that are not available can be shown below the available ones, making it easier to differentiate between them.

Additionally, I suggest highlighting the unavailable routes in bold with the label "No Route" to make the distinction clear (as in the example).

Another improvement would be to remove irrelevant routes, such as the option "From Celestia to Celestia" — which doesn't make sense since you cannot create a route to the same origin and destination.

![Frame 500](https://github.com/user-attachments/assets/708bb41a-5685-4d1a-9cd1-dd09d9e48ad0)

**Comment by jmrossy** [comment]
Fixed in https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/328
