### ISSUE TITLE
https://hyperlane-warp-template.vercel.app/ is broken

### ISSUE THREAD

**Issue by bap2pecs** [hyperlane-xyz/hyperlane-warp-ui-template#57]
![image](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/assets/111917526/bcef6671-6131-43ac-91ea-37238cca84d6)

**Comment by avious00** [comment]
hi @bap2pecs this should be fixed, but let me know if any issues pop up! im in our snapchain tg
