### ISSUE TITLE
Update to latest Wagmi + Rainbowkit

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-warp-ui-template#80]
We're stuck on older versions for Ethers V5 support.
We'd need to adapt the SDK txs for Viem, as that's what newer Wagmi versions require. 

Improves Warp UI wallet connection experience

**Comment by avious00** [comment]
captured in backlog

**Comment by jmrossy** [comment]
@tkporter mentioned as part of the hackathon feedback that our older wagmi version and the ethers-only SDK txs were a problem for some participants. I'm not surprised to hear that, it will probably happen more often as viem's popularity grows.

We can update SDK to be lib agnostic, or at least provide the utilities someone would need to adapter ethers<->viem. Viem itself has a bit of documentation about this but it doesn't cover everything we would need: 
https://wagmi.sh/core/ethers-adapters
https://github.com/wagmi-dev/wagmi/discussions/2340
